stages:
  - build
  - test

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

centos8:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  script:
    - yum install -y cc7/RPMS/*/*.rpm
    - gfal2-unit-tests

centos8-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  dependencies:
    - centos8
  script:
    - dnf install -y epel-release
    - dnf install -y centos8/RPMS/*/*.rpm
    - gfal2-unit-tests