stages:
  - build

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"
