stages:
  - build
  - test
  - publish

#--------------------------
# Build templates
#--------------------------

.build-template: &build-template_definition
  stage: build
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

#--------------------------
# Build jobs
#--------------------------

cc7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  <<: *build-template_definition

centos8:
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  <<: *build-template_definition

#--------------------------
# Test templates
#--------------------------

.test-template: &test-template_definition
  stage: test
  before_script:
    - declare -A DISTMAP=( [cc7]=el7 [centos8]=el8 )
    - PLATFORM=${CI_JOB_NAME%-*}
    - DIST=${DISTMAP[${PLATFORM}]}
    - if [[ "$CI_COMMIT_TAG" != null ]]; then BUILD="devel" ; else BUILD="rc" ; fi
    - cp -v ci/repo/dmc-${BUILD}-${DIST}.repo /etc/yum.repos.d/
  script:
    - dnf install -y epel-release
    - dnf install -y ${PLATFORM}/RPMS/*/*.rpm
    - gfal2-unit-tests

#--------------------------
# Test jobs
#--------------------------

cc7-test:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  <<: *test-template_definition

centos8-test:
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  dependencies:
    - centos8
  <<: *test-template_definition

#--------------------------
# Publish templates
#--------------------------

.publish-template: &publish-template_definition
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - cc7
    - centos8
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - eosfusebind
    - |
        for platform in cc7 centos8; do
          packaging/gfal2-repo-manager.py --action add --base /eos/project/d/dmc/www/repos/ --ref ${CI_COMMIT_REF_NAME} --packages ${platform}/RPMS/*/*.rpm ${platform}/SRPMS/*
        done
    - sleep 60
  tags:
    - docker-privileged
  retry: 2

#--------------------------
# Publish jobs
#--------------------------

rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_TAG!= null'

testing-rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME != "develop" && $CI_COMMIT_TAG == null'
      when: manual

publish-production:
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  script: 
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - eosfusebind
    - packaging/syncrepo --base-origin /eos/project/d/dmc/www/repos/rc --base-dest /eos/project/d/dmc/www/repos/ '*.rpm'
    - sleep 60
  tags:
    - docker-privileged
  retry: 2
  rules:
    - if: $CI_COMMIT_TAG != null
      when: manual
